-- Ajouter des descriptions a chaque champ config pour les tooltips dans l'app bureau.
-- On met a jour le config_schema de chaque bot_definition pour inclure un champ "description".

-- ══════════════════════════════════════════════
-- AUTOMOD-BOT
-- ══════════════════════════════════════════════
UPDATE bot_definitions SET config_schema = '[
  {"key":"enabled","label":"Active","type":"boolean","required":false,"default":"true","description":"Active ou desactive completement le bot automod sur ce serveur."},
  {"key":"spam_detection_enabled","label":"Detection spam","type":"boolean","required":false,"default":"true","description":"Detecte les messages repetes, caracteres en boucle et flood de mots."},
  {"key":"spam_repeat_char_threshold","label":"Seuil caracteres repetes","type":"number","required":false,"default":"6","description":"Nombre minimum de caracteres identiques consecutifs pour declencher la detection (ex: aaaaaa)."},
  {"key":"spam_repeat_word_threshold","label":"Seuil mots repetes","type":"number","required":false,"default":"5","description":"Nombre minimum de mots identiques pour declencher la detection spam."},
  {"key":"caps_warning_enabled","label":"Avertissement majuscules","type":"boolean","required":false,"default":"true","description":"Envoie un avertissement quand un message est ecrit entierement en MAJUSCULES."},
  {"key":"caps_threshold_chars","label":"Seuil majuscules","type":"number","required":false,"default":"8","description":"Nombre minimum de caracteres majuscules pour declencher l avertissement."},
  {"key":"insult_detection_enabled","label":"Detection insultes","type":"boolean","required":false,"default":"true","description":"Detecte les insultes en francais et anglais, y compris les variantes leet speak."},
  {"key":"insult_custom_words","label":"Mots personnalises","type":"text","required":false,"default":"","description":"Liste de mots interdits personnalises, separes par des virgules. Ex: noob,troll,spam"},
  {"key":"link_detection_enabled","label":"Detection liens","type":"boolean","required":false,"default":"true","description":"Detecte et filtre les liens non autorises (hors domaines en liste blanche)."},
  {"key":"allow_discord_invites","label":"Autoriser invitations Discord","type":"boolean","required":false,"default":"false","description":"Si desactive, les liens discord.gg seront supprimes."},
  {"key":"allowed_domains","label":"Domaines autorises","type":"text","required":false,"default":"","description":"Domaines autorises (separes par virgules). Ex: youtube.com,twitch.tv,twitter.com"},
  {"key":"phishing_detection_enabled","label":"Detection phishing","type":"boolean","required":false,"default":"true","description":"Detecte les liens de phishing (faux sites Discord, Steam, etc.)."},
  {"key":"phishing_extra_whitelist","label":"Whitelist phishing","type":"text","required":false,"default":"","description":"Domaines supplementaires a ne pas considerer comme phishing (virgules)."},
  {"key":"emoji_spam_enabled","label":"Detection emoji spam","type":"boolean","required":false,"default":"true","description":"Detecte les messages contenant un nombre excessif d emojis."},
  {"key":"emoji_spam_max","label":"Max emojis","type":"number","required":false,"default":"10","description":"Nombre maximum d emojis autorises par message avant detection."},
  {"key":"mentions_enabled","label":"Detection mentions","type":"boolean","required":false,"default":"true","description":"Detecte les messages avec trop de mentions (@user)."},
  {"key":"mentions_max","label":"Max mentions","type":"number","required":false,"default":"5","description":"Nombre maximum de mentions par message avant detection."},
  {"key":"suspicious_files_enabled","label":"Detection fichiers suspects","type":"boolean","required":false,"default":"true","description":"Supprime les fichiers avec extensions dangereuses (.exe, .bat, .ps1, etc.)."},
  {"key":"suspicious_file_extensions","label":"Extensions suspectes","type":"text","required":false,"default":"","description":"Extensions supplementaires a bloquer (virgules). Ex: apk,iso,torrent"},
  {"key":"unicode_detection_enabled","label":"Detection unicode","type":"boolean","required":false,"default":"true","description":"Detecte les caracteres Unicode invisibles ou de combinaison excessifs."},
  {"key":"unicode_max_combining","label":"Max combinaisons Unicode","type":"number","required":false,"default":"3","description":"Nombre maximum de caracteres combinants Unicode par caractere."},
  {"key":"unicode_max_invisible","label":"Max invisibles Unicode","type":"number","required":false,"default":"5","description":"Nombre maximum de caracteres invisibles (zero-width) par message."},
  {"key":"flood_max_messages","label":"Seuil flood (messages)","type":"number","required":false,"default":"5","description":"Nombre de messages dans la fenetre de temps pour declencher la detection flood."},
  {"key":"flood_window_secs","label":"Fenetre flood (secondes)","type":"number","required":false,"default":"10","description":"Duree de la fenetre de detection du flood en secondes."},
  {"key":"mute_duration_secs","label":"Duree mute (secondes)","type":"number","required":false,"default":"600","description":"Duree du mute automatique en secondes (defaut: 10 minutes)."},
  {"key":"night_mode_enabled","label":"Mode nuit","type":"boolean","required":false,"default":"false","description":"Active des seuils de detection plus stricts pendant les heures de nuit."},
  {"key":"night_start_hour","label":"Heure debut nuit","type":"number","required":false,"default":"22","description":"Heure UTC de debut du mode nuit (0-23)."},
  {"key":"night_end_hour","label":"Heure fin nuit","type":"number","required":false,"default":"8","description":"Heure UTC de fin du mode nuit (0-23)."},
  {"key":"adaptive_slowmode_enabled","label":"Slowmode adaptatif","type":"boolean","required":false,"default":"false","description":"Active automatiquement le slowmode sur un salon quand le volume de messages est trop eleve."},
  {"key":"adaptive_slowmode_threshold","label":"Seuil slowmode","type":"number","required":false,"default":"15","description":"Nombre de messages par fenetre de 30s pour activer le slowmode."},
  {"key":"adaptive_slowmode_seconds","label":"Duree slowmode","type":"number","required":false,"default":"5","description":"Duree du slowmode en secondes une fois active."},
  {"key":"log_channel_id","label":"Salon de logs","type":"channel","required":false,"default":"","description":"ID du salon ou les actions de moderation automatique seront enregistrees."},
  {"key":"ignored_channels","label":"Salons ignores","type":"text","required":false,"default":"","description":"IDs des salons ou l automod est desactive (separes par virgules)."},
  {"key":"ignored_roles","label":"Roles ignores","type":"text","required":false,"default":"","description":"IDs des roles immunises contre l automod (separes par virgules). Ex: moderateurs."},
  {"key":"color_warn","label":"Couleur avertissement","type":"text","required":false,"default":"f59e0b","description":"Code couleur hex pour les embeds d avertissement."},
  {"key":"color_delete","label":"Couleur suppression","type":"text","required":false,"default":"f97316","description":"Code couleur hex pour les embeds de suppression."},
  {"key":"color_mute","label":"Couleur mute","type":"text","required":false,"default":"ef4444","description":"Code couleur hex pour les embeds de mute."},
  {"key":"color_ban","label":"Couleur ban","type":"text","required":false,"default":"dc2626","description":"Code couleur hex pour les embeds de bannissement."}
]'::jsonb WHERE bot_name = 'automod-bot';

-- ══════════════════════════════════════════════
-- COUDE-BOT
-- ══════════════════════════════════════════════
UPDATE bot_definitions SET config_schema = '[
  {"key":"enabled","label":"Active","type":"boolean","required":false,"default":"true","description":"Active ou desactive le jeu Coup de Coude sur ce serveur."},
  {"key":"starting_coins","label":"Coins de depart","type":"number","required":false,"default":"200","description":"Nombre de coins donnes a chaque nouveau joueur."},
  {"key":"min_bet","label":"Mise minimum","type":"number","required":false,"default":"1","description":"Mise minimum autorisee pour les combats."},
  {"key":"max_bet","label":"Mise maximum","type":"number","required":false,"default":"0","description":"Mise maximum autorisee (0 = illimitee)."},
  {"key":"default_bet","label":"Mise par defaut","type":"number","required":false,"default":"10","description":"Mise utilisee quand le joueur ne specifie pas de montant."},
  {"key":"chaos_enabled","label":"Chaos active","type":"boolean","required":false,"default":"true","description":"Active les evenements chaos aleatoires pendant les combats."},
  {"key":"chaos_chance","label":"Chance chaos (%)","type":"number","required":false,"default":"18","description":"Probabilite qu un evenement chaos se declenche (en %)."},
  {"key":"casino_enabled","label":"Casino active","type":"boolean","required":false,"default":"true","description":"Active la commande /casino pour parier au hasard."},
  {"key":"casino_max_bet","label":"Mise max casino","type":"number","required":false,"default":"500","description":"Mise maximum au casino."},
  {"key":"steal_enabled","label":"Vol active","type":"boolean","required":false,"default":"true","description":"Active la commande /voler pour pickpocket d autres joueurs."},
  {"key":"steal_success_rate","label":"Taux de succes vol (%)","type":"number","required":false,"default":"30","description":"Probabilite de reussite du vol (en %). Les fourbes ont +20%."},
  {"key":"steal_cooldown_secs","label":"Cooldown vol (secondes)","type":"number","required":false,"default":"1800","description":"Temps d attente entre deux tentatives de vol (en secondes)."},
  {"key":"insurance_cost","label":"Cout assurance","type":"number","required":false,"default":"50","description":"Prix d une assurance contre les pertes de combat."},
  {"key":"insurance_duration_secs","label":"Duree assurance (secondes)","type":"number","required":false,"default":"3600","description":"Duree de validite d une assurance en secondes."},
  {"key":"insurance_scam_rate","label":"Taux arnaque assurance (%)","type":"number","required":false,"default":"5","description":"Probabilite que l assurance soit une arnaque (ne fonctionne pas)."},
  {"key":"cowardice_threshold","label":"Seuil lachete","type":"number","required":false,"default":"5","description":"Nombre de refus avant d etre marque comme lache (-20% gains)."},
  {"key":"cowardice_penalty","label":"Penalite lachete (%)","type":"number","required":false,"default":"20","description":"Pourcentage de reduction des gains pour les laches."},
  {"key":"refusal_penalty","label":"Penalite refus (%)","type":"number","required":false,"default":"20","description":"Pourcentage de coins perdus en refusant un defi."},
  {"key":"cancel_penalty","label":"Penalite annulation (%)","type":"number","required":false,"default":"5","description":"Pourcentage de coins perdus en annulant un defi initie."},
  {"key":"bet_delay_secs","label":"Delai paris (secondes)","type":"number","required":false,"default":"300","description":"Temps d attente apres acceptation pour que les joueurs puissent parier."},
  {"key":"daily_chaos_enabled","label":"Chaos quotidien","type":"boolean","required":false,"default":"true","description":"Active la roue du destin quotidienne (transfert aleatoire entre joueurs)."},
  {"key":"daily_chaos_percent","label":"Chaos quotidien (%)","type":"number","required":false,"default":"20","description":"Pourcentage de coins transferes lors du chaos quotidien."},
  {"key":"happy_hour_multiplier","label":"Multiplicateur happy hour","type":"number","required":false,"default":"2","description":"Multiplicateur de gains pendant les events happy hour."},
  {"key":"log_channel_id","label":"Salon de logs","type":"channel","required":false,"default":"","description":"ID du salon pour les logs du jeu."},
  {"key":"shop_explosion_price","label":"Prix Explosion","type":"number","required":false,"default":"200","description":"Prix de l item Explosion au shop (les deux perdent la mise)."},
  {"key":"shop_inversion_price","label":"Prix Inversion","type":"number","required":false,"default":"500","description":"Prix de l item Inversion au shop."},
  {"key":"shop_mindgame_price","label":"Prix Mindgame","type":"number","required":false,"default":"150","description":"Prix de l item Mindgame au shop."},
  {"key":"shop_rage_price","label":"Prix Rage","type":"number","required":false,"default":"100","description":"Prix de l item Rage au shop (+50% ATK)."},
  {"key":"shop_surprise_price","label":"Prix Surprise","type":"number","required":false,"default":"300","description":"Prix de l item Attaque Surprise au shop (auto-resolution)."},
  {"key":"shop_double_coup_price","label":"Prix Double Coup","type":"number","required":false,"default":"250","description":"Prix de l item Double Coup au shop (meilleur des 2 rolls)."},
  {"key":"shop_coup_traitre_price","label":"Prix Coup Traitre","type":"number","required":false,"default":"350","description":"Prix de l item Coup Traitre au shop (ignore la defense)."},
  {"key":"channel_combats","label":"Salon combats","type":"channel","required":false,"default":"","description":"Salon dedie aux defis et combats. Les commandes /coude et /pari y sont restreintes."},
  {"key":"channel_leaderboard","label":"Salon leaderboard","type":"channel","required":false,"default":"","description":"Salon dedie au classement. La commande /leaderboard y est restreinte."},
  {"key":"channel_profil","label":"Salon profil","type":"channel","required":false,"default":"","description":"Salon dedie aux profils joueurs. La commande /profil y est restreinte."},
  {"key":"channel_activites","label":"Salon activites","type":"channel","required":false,"default":"","description":"Salon ou sont postes les resultats de vol, casino, shop, assurance et entrainement."},
  {"key":"channel_announcements","label":"Salon annonces","type":"channel","required":false,"default":"","description":"Salon pour les evenements automatiques : daily chaos, happy hour, bloodbath."},
  {"key":"channel_notifications","label":"Salon notifications","type":"channel","required":false,"default":"","description":"Salon pour les alertes aux joueurs : nouveaux defis, paris ouverts."}
]'::jsonb WHERE bot_name = 'coude-bot';
