[package]
name = "atrium-bot"
version.workspace = true
edition.workspace = true
description = "Bot Discord d'accueil IA Atrium"

[dependencies]
serenity = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
atrium-proto = { workspace = true }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
platform-common = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
platform-common-bot = { version = "0.1.0", path = "../platform-common-bot" }

[lints]
workspace = true
